mdapipkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Average_Order_Value__c</fullName>
        <label>Average Order Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Earned__c</fullName>
        <label>Commission Earned</label>
        <summarizedField>Affiliate_Offer__c.Commissions_Earned__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Commissions_Paid_And_Refunded__c</fullName>
        <label>Commissions Paid And Refunded</label>
        <summarizedField>Affiliate_Offer__c.Commissions_Paid_And_Refunded__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Commissions_Paid__c</fullName>
        <label>Commissions Paid</label>
        <summarizedField>Affiliate_Offer__c.Commissions_Paid__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Commissions_Refunded__c</fullName>
        <label>Commissions Refunded</label>
        <summarizedField>Affiliate_Offer__c.Commissions_Refunded__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Refund_Transactions__c</fullName>
        <label>Refund Transactions</label>
        <summarizedField>Affiliate_Offer__c.Refund_Transactions__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Commissions__c</fullName>
        <label>Total Commissions</label>
        <summarizedField>Affiliate_Offer__c.Total_Commissions__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Revenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>Affiliate_Offer__c.Total_Revenue__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Transactions__c</fullName>
        <label>Total Transactions</label>
        <summarizedField>Affiliate_Offer__c.Total_Transactions__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

mdapipkg/objects/Affiliate_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliate Offers</relationshipLabel>
        <relationshipName>Affiliate_Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commission_Not_Passed_Refund_Period__c</fullName>
        <label>Commissions Not Passed Refund Period</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissions_Earned__c</fullName>
        <label>Commissions Earned</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissions_Earned_for_Withdrawal__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Commissions Available for Withdrawal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissions_Paid_And_Refunded__c</fullName>
        <label>Commissions Paid and Refunded</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissions_Paid__c</fullName>
        <label>Commissions Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissions_Pending_Withdrawal__c</fullName>
        <label>Commissions Pending Withdrawal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissions_Refunded__c</fullName>
        <label>Commissions Refunded</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Affiliate Offers</relationshipLabel>
        <relationshipName>Affiliate_Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Refund_Transactions__c</fullName>
        <label>Refund Transactions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Commissions__c</fullName>
        <label>Total Commissions</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Revenue__c</fullName>
        <label>Total Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Transactions__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Transactions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Affiliate Offer</label>
    <nameField>
        <displayFormat>AFO-{000}</displayFormat>
        <label>Affiliate Offer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliate Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/objects/Commissions_Earned__c.object
<CustomObject>
    <fields>
        <fullName>Affiliate_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affiliate Offer</label>
        <referenceTo>Affiliate_Offer__c</referenceTo>
        <relationshipLabel>Commissions Earned</relationshipLabel>
        <relationshipName>Commissions_Earned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Earned__c</fullName>
        <label>Commission Earned</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Commissions Earned</relationshipLabel>
        <relationshipName>Commissions_Earned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Commissions Earned</relationshipLabel>
        <relationshipName>Commissions_Earned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Available for Withdrawal</fullName>
                </value>
                <value>
                    <fullName>Not Available for Withdrawal</fullName>
                    <default>true</default>
                    <label>Not Available for Withdrawal</label>
                </value>
                <value>
                    <fullName>Pending Withdrawal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Commissions Earned</label>
    <nameField>
        <displayFormat>COE-{000}</displayFormat>
        <label>Commissions Earned Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions Earned</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Commission_Earned__c</fullName>
        <label>Commission Earned</label>
        <summarizedField>Affiliate_Offer__c.Commissions_Earned__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Offer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Commissions_Paid_And_Refunded__c</fullName>
        <label>Commissions Paid and Refunded</label>
        <summarizedField>Affiliate_Offer__c.Commissions_Paid_And_Refunded__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Offer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Commissions_Pending_Withdrawal__c</fullName>
        <label>Commissions Pending Withdrawal</label>
        <summarizedField>Affiliate_Offer__c.Commissions_Pending_Withdrawal__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Offer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Commissions_Refunded__c</fullName>
        <label>Commissions Refunded</label>
        <summarizedField>Affiliate_Offer__c.Commissions_Refunded__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Offer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Refund_Transactions__c</fullName>
        <label>Refund Transactions</label>
        <summarizedField>Affiliate_Offer__c.Refund_Transactions__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Offer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Commissions__c</fullName>
        <label>Total Commissions</label>
        <summarizedField>Affiliate_Offer__c.Total_Commissions__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Offer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Revenue__c</fullName>
        <label>Total Revenue</label>
        <summarizedField>Affiliate_Offer__c.Total_Revenue__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Offer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Transactions__c</fullName>
        <label>Total Transactions</label>
        <summarizedField>Affiliate_Offer__c.Total_Transactions__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Offer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFR-{000}</displayFormat>
        <label>Offer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{000000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/classes/AffiliateOfferTriggerTest.cls
@isTest
private class AffiliateOfferTriggerTest {

	// method name: checkForDublicate
	// created: 01/24/2018
	// Author: Stanislau Yarashchuk
	// Create dublicate Affiliate Offer 
	@isTest static void checkForDublicate() {

		List<RecordType> personRecordTypeList = [
			SELECT Id, Name, SobjectType, IsPersonType
			FROM RecordType
			WHERE SobjectType = 'Account' AND DeveloperName = 'Affiliate_Account' AND IsPersonType = true AND IsActive = true
		];

		System.assertEquals(!personRecordTypeList.isEmpty(), true);

		List<Account> accountList = new List<Account>();
		for (Integer i = 0; i < 200; i++) {
			accountList.add(
				new Account(
					RecordTypeId = personRecordTypeList[0].Id, LastName = 'lastName'+i, FirstName = 'FirstName'+i, PersonEmail = 'testA@gmail'+i+'.com', Phone = '123456789'+i
				)
			);
		}
		insert accountList;
		System.assertEquals(accountList.size(), 200);

		List<Offer__c> offerList = new List<Offer__c>();
		for (Integer i = 0; i < 200; i++) {
			offerList.add(
				new Offer__c(
					Active__c = true
				)
			);
		}
		insert offerList;
		System.assertEquals(offerList.size(), 200);


		List<Affiliate_Offer__c> affiliateOfferList = new List<Affiliate_Offer__c>();
		for (Integer i = 0; i < 200; i++) {
			affiliateOfferList.add(
				new Affiliate_Offer__c(
					Account__c = accountList[i].Id, Offer__c = offerList[0].Id
				)
			);
		}
		insert affiliateOfferList;
		System.assertEquals(affiliateOfferList.size(), 200);

		try {
			List<Affiliate_Offer__c> affiliateOfferNewList = new List<Affiliate_Offer__c>();
			for (Integer i = 0; i < 200; i++) {
				affiliateOfferNewList.add(
					new Affiliate_Offer__c(
						Account__c = accountList[i].Id, Offer__c = offerList[0].Id
					)
				);
			}
			insert affiliateOfferNewList;
		} catch(Exception e) {
			System.AssertEquals(e.getMessage().contains('Duplicate record'), true);
		}

	}

	// method name: checkForDublicate
	// created: 01/25/2018
	// Author: Stanislau Yarashchuk
	// Create commissions earned for calculate comissions on the Affiliate Offer record
	@isTest static void recalculateAffiliateOffer1() {

		List<RecordType> personRecordTypeList = [
			SELECT Id, Name, SobjectType, IsPersonType
			FROM RecordType
			WHERE SobjectType = 'Account' AND DeveloperName = 'Affiliate_Account' AND IsPersonType = true AND IsActive = true
		];


		List<Account> accountList = new List<Account>();
		for (Integer i = 0; i < 200; i++) {
			accountList.add(
				new Account(
					RecordTypeId = personRecordTypeList[0].Id, LastName = 'lastName'+i, FirstName = 'FirstName'+i, PersonEmail = 'testA@gmail'+i+'.com', Phone = '123456789'+i
				)
			);
		}
		insert accountList;
		System.assertEquals(accountList.size(), 200);

		List<Offer__c> offerList = new List<Offer__c>();
		for (Integer i = 0; i < 200; i++) {
			offerList.add(
				new Offer__c(
					Active__c = true
				)
			);
		}
		insert offerList;
		System.assertEquals(offerList.size(), 200);


		List<Affiliate_Offer__c> affiliateOfferList = new List<Affiliate_Offer__c>();
		for (Integer i = 0; i < 200; i++) {
			affiliateOfferList.add(
				new Affiliate_Offer__c(
					Account__c = accountList[i].Id, Offer__c = offerList[0].Id
				)
			);
		}
		insert affiliateOfferList;
		System.assertEquals(affiliateOfferList.size(), 200);

		List<TouchCRBase__Order__c> orderList = new List<TouchCRBase__Order__c>();
		for (Integer i = 0; i < 200; i++) {
			orderList.add(
				new TouchCRBase__Order__c(
					TouchCRBase__Subtotal__c = 100
				)
			);
		}
		insert orderList;
		System.assertEquals(orderList.size(), 200);

		List<Commissions_Earned__c> commissionEarnedList = new List<Commissions_Earned__c>();
		for (Integer i = 0; i < 200; i++) {
			commissionEarnedList.add(
				new Commissions_Earned__c(
					Affiliate_Offer__c = affiliateOfferList[0].Id,
					Commission_Earned__c = 10,
					Offer__c = offerList[0].Id,
					Order__c = orderList[i].Id,
					Price__c = 100,
					Status__c = 'Not Available for Withdrawal',
					Type__c = 'Sales'
				)
			);
		}
		insert commissionEarnedList;
		System.assertEquals(commissionEarnedList.size(), 200);

		List<Affiliate_Offer__c> affiliateOfferCalculated = [
			SELECT Id, Name, Commissions_Earned__c, Commissions_Earned_for_Withdrawal__c, Commissions_Paid__c, Commissions_Refunded__c,
				Total_Commissions__c, Commissions_Paid_And_Refunded__c, Commission_Not_Passed_Refund_Period__c, Commissions_Pending_Withdrawal__c, 
				Total_Transactions__c, Refund_Transactions__c, Total_Revenue__c, Average_Order_Value__c
			FROM Affiliate_Offer__c
			WHERE Id = :affiliateOfferList[0].Id
		];

		System.assertEquals(affiliateOfferCalculated[0].Commissions_Earned__c, 2000);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Earned_for_Withdrawal__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Paid__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Refunded__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Total_Commissions__c, 2000);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Paid_And_Refunded__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Commission_Not_Passed_Refund_Period__c, 2000);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Pending_Withdrawal__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Total_Transactions__c, 200);
		System.assertEquals(affiliateOfferCalculated[0].Refund_Transactions__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Total_Revenue__c, 20000);
		System.assertEquals(affiliateOfferCalculated[0].Average_Order_Value__c, 100);

		for (Commissions_Earned__c item : commissionEarnedList) {
			item.Status__c = 'Available for Withdrawal';
		}
		update commissionEarnedList;

		affiliateOfferCalculated = [
			SELECT Id, Name, Commissions_Earned__c, Commissions_Earned_for_Withdrawal__c, Commissions_Paid__c, Commissions_Refunded__c,
				Total_Commissions__c, Commissions_Paid_And_Refunded__c, Commission_Not_Passed_Refund_Period__c, Commissions_Pending_Withdrawal__c, 
				Total_Transactions__c, Refund_Transactions__c, Total_Revenue__c, Average_Order_Value__c
			FROM Affiliate_Offer__c
			WHERE Id = :affiliateOfferList[0].Id
		];

		System.assertEquals(affiliateOfferCalculated[0].Commissions_Earned__c, 2000);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Earned_for_Withdrawal__c, 2000);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Paid__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Refunded__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Total_Commissions__c, 2000);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Paid_And_Refunded__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Commission_Not_Passed_Refund_Period__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Pending_Withdrawal__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Total_Transactions__c, 200);
		System.assertEquals(affiliateOfferCalculated[0].Refund_Transactions__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Total_Revenue__c, 20000);
		System.assertEquals(affiliateOfferCalculated[0].Average_Order_Value__c, 100);


		for (Commissions_Earned__c item : commissionEarnedList) {
			item.Status__c = 'Pending Withdrawal';
		}
		update commissionEarnedList;

		affiliateOfferCalculated = [
			SELECT Id, Name, Commissions_Earned__c, Commissions_Earned_for_Withdrawal__c, Commissions_Paid__c, Commissions_Refunded__c,
				Total_Commissions__c, Commissions_Paid_And_Refunded__c, Commission_Not_Passed_Refund_Period__c, Commissions_Pending_Withdrawal__c, 
				Total_Transactions__c, Refund_Transactions__c, Total_Revenue__c, Average_Order_Value__c
			FROM Affiliate_Offer__c
			WHERE Id = :affiliateOfferList[0].Id
		];

		System.assertEquals(affiliateOfferCalculated[0].Commissions_Earned__c, 2000);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Earned_for_Withdrawal__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Paid__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Refunded__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Total_Commissions__c, 2000);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Paid_And_Refunded__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Commission_Not_Passed_Refund_Period__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Pending_Withdrawal__c, 2000);
		System.assertEquals(affiliateOfferCalculated[0].Total_Transactions__c, 200);
		System.assertEquals(affiliateOfferCalculated[0].Refund_Transactions__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Total_Revenue__c, 20000);
		System.assertEquals(affiliateOfferCalculated[0].Average_Order_Value__c, 100);

		for (Commissions_Earned__c item : commissionEarnedList) {
			item.Status__c = 'Refund';
			item.Paid__c = true;
		}
		update commissionEarnedList;

		affiliateOfferCalculated = [
			SELECT Id, Name, Commissions_Earned__c, Commissions_Earned_for_Withdrawal__c, Commissions_Paid__c, Commissions_Refunded__c,
				Total_Commissions__c, Commissions_Paid_And_Refunded__c, Commission_Not_Passed_Refund_Period__c, Commissions_Pending_Withdrawal__c, 
				Total_Transactions__c, Refund_Transactions__c, Total_Revenue__c, Average_Order_Value__c
			FROM Affiliate_Offer__c
			WHERE Id = :affiliateOfferList[0].Id
		];

		System.assertEquals(affiliateOfferCalculated[0].Commissions_Earned__c, 2000);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Earned_for_Withdrawal__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Paid__c, 2000);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Refunded__c, -2000);
		System.assertEquals(affiliateOfferCalculated[0].Total_Commissions__c, 2000);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Paid_And_Refunded__c, -2000);
		System.assertEquals(affiliateOfferCalculated[0].Commission_Not_Passed_Refund_Period__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Commissions_Pending_Withdrawal__c, 0);
		System.assertEquals(affiliateOfferCalculated[0].Total_Transactions__c, 200);
		System.assertEquals(affiliateOfferCalculated[0].Refund_Transactions__c, 200);
		System.assertEquals(affiliateOfferCalculated[0].Total_Revenue__c, 20000);
		System.assertEquals(affiliateOfferCalculated[0].Average_Order_Value__c, 100);
	}
}