mdapipkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Commission_Earned__c</fullName>
        <label>Commission Earned</label>
        <summarizedField>Affiliate_Offer__c.Commissions_Earned__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

mdapipkg/objects/Affiliate_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliate Offers</relationshipLabel>
        <relationshipName>Affiliate_Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commissions_Earned__c</fullName>
        <label>Commissions Earned</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Affiliate Offers</relationshipLabel>
        <relationshipName>Affiliate_Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sub1__c</fullName>
        <label>Sub1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Affiliate Offer</label>
    <nameField>
        <displayFormat>AFO-{000}</displayFormat>
        <label>Affiliate Offer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliate Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/objects/Commissions_Earned__c.object
<CustomObject>
    <fields>
        <fullName>Affiliate_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affiliate Offer</label>
        <referenceTo>Affiliate_Offer__c</referenceTo>
        <relationshipLabel>Commissions Earned</relationshipLabel>
        <relationshipName>Commissions_Earned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Earned__c</fullName>
        <label>Commission Earned</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Commissions Earned</relationshipLabel>
        <relationshipName>Commissions_Earned</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commissions Earned</label>
    <nameField>
        <displayFormat>COE-{000}</displayFormat>
        <label>Commissions Earned Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions Earned</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Commission_Earned__c</fullName>
        <label>Commission Earned</label>
        <summarizedField>Affiliate_Offer__c.Commissions_Earned__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Offer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Commission_Payable__c</fullName>
        <label>Commission Payable</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFR-{000}</displayFormat>
        <label>Offer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CommissionsEarnedTriggerTest.cls
@isTest
private class CommissionsEarnedTriggerTest {

	@isTest static void commissionsEarnedAndAffiliateOffer() {
		RecordType customerRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Customer_Account' AND IsPersonType = true];

		Account accA = new Account(RecordTypeId = customerRecordType.Id, LastName = 'AAccount', FirstName = 'First', PersonEmail = 'testA@gmail.com', Phone = '1234567890');
		insert accA;

		Offer__c offerA = new Offer__c(Commission_Payable__c = 20, Active__c = true);
		insert offerA;

		Affiliate_Offer__c affiliateOfferA = new Affiliate_Offer__c(Account__c = accA.Id, Offer__c = offerA.Id, Sub1__c = 'Sub11', Commissions_Earned__c = 15);
		insert affiliateOfferA;


		//Trigger.isAfter && Trigger.isInsert
		Commissions_Earned__c commissionsEarnedA = new Commissions_Earned__c(Affiliate_Offer__c = affiliateOfferA.id, Offer__c = offerA.Id, Commission_Earned__c = 10);
		insert commissionsEarnedA;

		Affiliate_Offer__c affiliateOfferTestA = [SELECT Id, Commissions_Earned__c FROM Affiliate_Offer__c LIMIT 1];
		System.assertEquals(10, affiliateOfferTestA.Commissions_Earned__c);

		//Trigger.isAfter && Trigger.isUpdate
		commissionsEarnedA.Commission_Earned__c = 20;
		update commissionsEarnedA;
		Affiliate_Offer__c affiliateOfferTestB = [SELECT Id, Commissions_Earned__c FROM Affiliate_Offer__c LIMIT 1];
		System.assertEquals(20, affiliateOfferTestB.Commissions_Earned__c);

		//Trigger.isAfter && Trigger.isDelete
		delete commissionsEarnedA;
		Affiliate_Offer__c affiliateOfferTestC = [SELECT Id, Commissions_Earned__c FROM Affiliate_Offer__c LIMIT 1];
		System.assertEquals(0, affiliateOfferTestC.Commissions_Earned__c);

	}

}