mdapipkg/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Available_Balance__c</fullName>
        <label>Available Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Earned__c</fullName>
        <label>Commission Earned</label>
        <summarizedField>Affiliate_Offer__c.Commissions_Earned__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

mdapipkg/objects/Affiliate_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliate Offers</relationshipLabel>
        <relationshipName>Affiliate_Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commissions_Earned__c</fullName>
        <label>Commissions Earned</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissions_Earned_for_Withdrawal__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Commissions Available for Withdrawal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Affiliate Offers</relationshipLabel>
        <relationshipName>Affiliate_Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Affiliate Offer</label>
    <nameField>
        <displayFormat>AFO-{000}</displayFormat>
        <label>Affiliate Offer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliate Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/objects/Commissions_Earned__c.object
<CustomObject>
    <fields>
        <fullName>Affiliate_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Affiliate Offer</label>
        <referenceTo>Affiliate_Offer__c</referenceTo>
        <relationshipLabel>Commissions Earned</relationshipLabel>
        <relationshipName>Commissions_Earned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Earned__c</fullName>
        <label>Commission Earned</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Commissions Earned</relationshipLabel>
        <relationshipName>Commissions_Earned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payouts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payout</label>
        <referenceTo>Payouts__c</referenceTo>
        <relationshipLabel>Commissions Earned</relationshipLabel>
        <relationshipName>Commissions_Earned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Available for Withdrawal</fullName>
                </value>
                <value>
                    <fullName>Not Available for Withdrawal</fullName>
                    <default>true</default>
                    <label>Not Available for Withdrawal</label>
                </value>
                <value>
                    <fullName>Pending Withdrawal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Commissions Earned</label>
    <nameField>
        <displayFormat>COE-{000}</displayFormat>
        <label>Commissions Earned Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions Earned</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Commission_Earned__c</fullName>
        <label>Commission Earned</label>
        <summarizedField>Affiliate_Offer__c.Commissions_Earned__c</summarizedField>
        <summaryForeignKey>Affiliate_Offer__c.Offer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Commission_Payable__c</fullName>
        <label>Commission Payable</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFR-{000}</displayFormat>
        <label>Offer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/Payouts__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payouts</relationshipLabel>
        <relationshipName>Payouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount_Transferred__c</fullName>
        <label>Amount Transferred</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting For Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payouts</label>
    <nameField>
        <displayFormat>PAT-{000}</displayFormat>
        <label>Payouts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PayoutTriggerTest.cls
@isTest
private class PayoutTriggerTest {

	@isTest static void testPayoutTrigger() {

		//Trigger.isBefore && Trigger.isInsert
		RecordType customerRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Customer_Account' AND IsPersonType = true];

		Account accA = new Account(RecordTypeId = customerRecordType.Id, LastName = 'AAccount', FirstName = 'First', PersonEmail = 'testA@gmail.com', Phone = '1234567890', Available_Balance__c = 10);
		Account accB = new Account(RecordTypeId = customerRecordType.Id, LastName = 'BAccount', FirstName = 'First', PersonEmail = 'testB@gmail.com', Phone = '1234567890', Available_Balance__c = 20);
		Account accC = new Account(RecordTypeId = customerRecordType.Id, LastName = 'CAccount', FirstName = 'First', PersonEmail = 'testC@gmail.com', Phone = '1234567890', Available_Balance__c = 30);
		insert new List<Account> {accA, accB, accC};

		Offer__c offerA = new Offer__c(Commission_Payable__c = 10, Active__c = true);
		Offer__c offerB = new Offer__c(Commission_Payable__c = 20, Active__c = true);
		insert new List<Offer__c> {offerA, offerB};

		Affiliate_Offer__c affiliateOfferA = new Affiliate_Offer__c(Account__c = accA.Id, Offer__c = offerA.Id, Commissions_Earned_for_Withdrawal__c = 10);
		Affiliate_Offer__c affiliateOfferB = new Affiliate_Offer__c(Account__c = accB.Id, Offer__c = offerB.Id, Commissions_Earned_for_Withdrawal__c = 20);
		insert new List<Affiliate_Offer__c> {affiliateOfferA, affiliateOfferB};

		Payouts__c payoutA = new Payouts__c (Account__c = accA.Id, Amount_Transferred__c = 10, Status__c = 'Waiting For Approval');
		insert payoutA;

		Payouts__c payoutInserted = [SELECT Id, Amount_Transferred__c FROM Payouts__c LIMIT 1];
		System.assertEquals(payoutInserted.Amount_Transferred__c, 10);


		//Trigger.isAfter && Trigger.isUpdate
		Commissions_Earned__c commissionEarnedA = new Commissions_Earned__c(Affiliate_Offer__c = affiliateOfferA.Id, Commission_Earned__c = 10, Payouts__c = payoutA.Id);
		insert commissionEarnedA;

		payoutA.Status__c = 'Approved';
		update payoutA;

		Commissions_Earned__c commissionA = [SELECT Id, Status__c, Payouts__r.Status__c FROM Commissions_Earned__c WHERE Payouts__c =:payoutA.Id LIMIT 1];
		System.assertEquals(commissionA.Status__c, 'Paid');


		//Trigger.isAfter && Trigger.isInsert
		Commissions_Earned__c commissionEarnedB = new Commissions_Earned__c(Affiliate_Offer__c = affiliateOfferB.Id, Commission_Earned__c = 20, Status__c = 'Available for Withdrawal', Type__c = 'Sales');
		insert commissionEarnedB;
		Payouts__c payoutB = new Payouts__c (Account__c = accB.Id, Amount_Transferred__c = 20, Status__c = 'Waiting For Approval');
		insert payoutB;
		Commissions_Earned__c commissionTest = [SELECT Id, Payouts__c, Status__c FROM Commissions_Earned__c WHERE Affiliate_Offer__c =: affiliateOfferB.Id LIMIT 1];
		System.AssertEquals(commissionTest.Status__c, 'Pending Withdrawal');


		//Trigger.isBefore && Trigger.isInsert Error
		try {
			Payouts__c payoutC = new Payouts__c (Account__c = accC.Id, Amount_Transferred__c = 10, Status__c = 'Waiting For Approval');
			insert payoutC;
		} catch (Exception e){
			Boolean expectedExceptionThrown = (e.getMessage().contains('The amount of the transfer')) ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
		}

	}

}