mdapipkg/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Commission_Payable__c</fullName>
        <label>Commission Payable</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offer_Name__c</fullName>
        <label>Offer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percent_Of_Price__c</fullName>
        <label>Percent Of Price</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFR-{000}</displayFormat>
        <label>Offer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <recordTypes>
        <fullName>Cart</fullName>
        <active>true</active>
        <label>Cart</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OfferTriggerTest.cls
@isTest
private class OfferTriggerTest {

	//OfferTrigger Test
	@isTest static void testCommissionPayable() {

		RecordType recordTypeItem = [SELECT Id FROM RecordType WHERE DeveloperName = 'Cart' LIMIT 1];

		Product2 iceCreamProduct = new Product2(Name = 'iceCreamProduct', ProductCode = 'iceCreamProductCode', IsActive = true );
		Product2 hotCreamProduct = new Product2(Name = 'hotCreamProduct', ProductCode = 'hotCreamProductCode', IsActive = true );
		insert new List<Product2> {iceCreamProduct, hotCreamProduct};

		Id pricebookId = Test.getStandardPricebookId();
		Pricebook2 pricebook2StandardName = new Pricebook2(Name = 'Standard Price Book', IsActive = true);
		insert pricebook2StandardName;

		PricebookEntry bookEntryA = new PricebookEntry (Product2Id = iceCreamProduct.Id, UnitPrice = 100, IsActive = true, Pricebook2Id = pricebookId);
		PricebookEntry bookEntryB = new PricebookEntry (Product2Id = iceCreamProduct.Id, UnitPrice = 100, IsActive = true, Pricebook2Id = pricebook2StandardName.Id);

		PricebookEntry bookEntryC = new PricebookEntry (Product2Id = hotCreamProduct.Id, UnitPrice = 200, IsActive = true, Pricebook2Id = pricebookId);
		PricebookEntry bookEntryD = new PricebookEntry (Product2Id = hotCreamProduct.Id, UnitPrice = 200, IsActive = true, Pricebook2Id = pricebook2StandardName.Id);
		insert new List<PricebookEntry> {bookEntryA, bookEntryB, bookEntryC, bookEntryD};

		Offer__c offerA = new Offer__c(Active__c = false, Offer_Name__c = 'offerA', Commission_Payable__c = 10, Percent_Of_Price__c = 20, Product__c = iceCreamProduct.Id, RecordTypeId = recordTypeItem.Id);
		Offer__c offerB = new Offer__c(Active__c = false, Offer_Name__c = 'offerB', Commission_Payable__c = 10, Product__c = hotCreamProduct.Id, RecordTypeId = recordTypeItem.Id);
		insert new List<Offer__c> {offerA, offerB};

		offerA.Active__c = true;
		update new List<Offer__c> {offerA, offerB};

		Offer__c testOfferA = [SELECT Id, Commission_Payable__c FROM Offer__c WHERE Offer_Name__c = 'offerA' LIMIT 1];
		System.assertEquals(20, testOfferA.Commission_Payable__c);
		Offer__c testOfferB = [SELECT Id, Commission_Payable__c FROM Offer__c WHERE Offer_Name__c = 'offerB' LIMIT 1];
		System.assertEquals(10, testOfferB.Commission_Payable__c);
	}

}