mdapipkg/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charge_Amount__c</fullName>
        <label>Charge Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Named_Agent__c</fullName>
        <inlineHelpText>Choose Named Agent for payment process</inlineHelpText>
        <label>Named Agent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{000000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/Order_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Named_Agent__c</fullName>
        <label>Named Agent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Response_Status__c</fullName>
        <label>Response Status</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Charge</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Profile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRX-{000000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/objects/Payment_Information__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Information</relationshipLabel>
        <relationshipName>Payment_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Information__c</fullName>
        <label>Information</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidBy__c</fullName>
        <label>Valid By</label>
        <type>Date</type>
    </fields>
    <label>Payment Information</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>Payment Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/Payment_Option__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Options</relationshipLabel>
        <relationshipName>Payment_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Named_Agent__c</fullName>
        <label>Named Agent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_Id__c</fullName>
        <label>Option Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Information</label>
        <referenceTo>Payment_Information__c</referenceTo>
        <relationshipLabel>Payment Options</relationshipLabel>
        <relationshipName>Payment_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Option</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Payment Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/classes/TouchCRAuraActionControllerTest.cls
@isTest
private class TouchCRAuraActionControllerTest {

	//VOID
	@isTest static void voidTestLighting() {
		RecordType customerRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Customer_Account' AND IsPersonType = true];
		Account acc = new Account(
			RecordTypeId = customerRecordType.Id,
			LastName = 'Gerdegedi', FirstName = 'Itsig',
			PersonEmail = 'Gerdegedi.Itsig@gmail.com', Phone = '1234567890',
			BillingStreet = 'Vulture St, Woolloongabba', BillingCity = 'Brisbane',
			BillingState = 'Queensland', BillingPostalCode = '4102',
			BillingCountry = 'Australia', ShippingStreet = 'Vulture St, Woolloongabba',
			ShippingCity = 'Brisbane', ShippingState = 'Queensland',
			ShippingPostalCode = '4102', ShippingCountry = 'Australia'
			//Geolocation__Longitude__s = 153.062496, Geolocation__Latitude__s = -27.579233
		);
		insert acc;

		Order__c order = new Order__c(
			Charge_Amount__c = 1,
			Account__c = acc.Id
		);
		insert order;
		
		Order_Transaction__c testTrans = new Order_Transaction__c(
			Order__c = order.Id,
			Named_Agent__c = 'Test Agent Name',
			Type__c = 'Charge',
			Response_Status__c = 'Approved',
			Payment_Date__c = Datetime.now(),
			Amount__c = 1
		);
		insert testTrans;

		Decimal amount = TouchCRAuraActionController.getAmountVoid(testTrans.Id);
		System.assertEquals(1, amount);

		String resultVoid = TouchCRAuraActionController.voidNow(testTrans.Id, 1);
		System.assertEquals(true, resultVoid.containsIgnoreCase('Your transaction has been approved.'));
	}


	//CHARGE
	@isTest static void chargeTest() {
		RecordType customerRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Customer_Account' AND IsPersonType = true];
		Account acc = new Account(RecordTypeId = customerRecordType.Id, LastName = 'Barack', PersonEmail = 'barack123@mail.com');
		insert acc;

		Date validBy = Date.newInstance(2021, 11, 1);

		Payment_Information__c paymentInformation = new Payment_Information__c(
			ValidBy__c = validBy, Information__c = '', Number__c = '4242', Account__c = acc.Id
		);
		insert paymentInformation;

		Payment_Option__c pO = new Payment_Option__c(
			Account__c = acc.Id, Last_4__c = '4242', Payment_Information__c = paymentInformation.Id,
			Named_Agent__c = 'TouchCRAgent', Option_Id__c = 'card_1BLxQaBtLSRuiG8TeSq0hPwu', 
			Profile_Id__c = 'cus_BjppUFrz7daGx4', Status__c = 'Active'
		);
		Payment_Option__c pO1 = new Payment_Option__c(
			Account__c = acc.Id, Last_4__c = '4242', Payment_Information__c = paymentInformation.Id,
			Named_Agent__c = 'TouchCRAgent', Option_Id__c = 'card_1BLxQaBtLSRuiG8TeSq0hPwu', 
			Profile_Id__c = 'cus_BjppUFrz7daGx4', Status__c = 'Inactive'
		); 
		insert new List<Payment_Option__c>{pO, pO1};

		Order__c testOrdCrarge = new Order__c(
			Charge_Amount__c = 2, Account__c = acc.Id, 
			Named_Agent__c = 'TouchCRAgent'
		);
		insert testOrdCrarge;

		String resultCardsAndGeneralInfo = TouchCRAuraActionController.getCardsAndGeneralInfo(testOrdCrarge.Id);
		ResultWrapper chargeDataWrapper = (ResultWrapper)JSON.deserialize(resultCardsAndGeneralInfo, ResultWrapper.class);
			
		System.assertEquals('success', chargeDataWrapper.status);
		System.assertEquals(2, chargeDataWrapper.amount);

		resultCardsAndGeneralInfo = TouchCRAuraActionController.getCardsAndGeneralInfo('');
		chargeDataWrapper = (ResultWrapper)JSON.deserialize(resultCardsAndGeneralInfo, ResultWrapper.class);
			
		System.assertEquals('error', chargeDataWrapper.status);

		Map<String, String> chargeData = new Map<String, String>{
			'amount' => '2',
			'orderId' => String.valueOf(testOrdCrarge.Id),
			'month' => '01',
			'newCard' => 'true'
		};

		String resultChargeOrderNow = TouchCRAuraActionController.chargeOrderNow(JSON.serialize(chargeData));
		ResultWrapper chargeOrderWrapper = (ResultWrapper)JSON.deserialize(resultChargeOrderNow, ResultWrapper.class);
		
		System.assertEquals('error', chargeOrderWrapper.status);    
		System.assertEquals('Data is not valid', chargeOrderWrapper.error); 

		chargeData = new Map<String, String>{
			'amount' => '2',
			'orderId' => String.valueOf(testOrdCrarge.Id),
			'newCard' => 'false'
		};

		resultChargeOrderNow = TouchCRAuraActionController.chargeOrderNow(JSON.serialize(chargeData));
		chargeOrderWrapper = (ResultWrapper)JSON.deserialize(resultChargeOrderNow, ResultWrapper.class);

		System.assertEquals('error', chargeOrderWrapper.status);    

		chargeData = new Map<String, String>{
			'orderId' => String.valueOf(testOrdCrarge.Id),
			'newCard' => 'false',
			'chosenPaymentOptionId' => String.valueOf(pO.Id)
		};

		resultChargeOrderNow = TouchCRAuraActionController.chargeOrderNow(JSON.serialize(chargeData));
		chargeOrderWrapper = (ResultWrapper)JSON.deserialize(resultChargeOrderNow, ResultWrapper.class);

		System.assertEquals('error', chargeOrderWrapper.status);    
		System.assertEquals('The Amount must not be less than 1 Dollar', chargeOrderWrapper.error); 

		chargeData = new Map<String, String>{
			'amount' => '2',
			'orderId' => String.valueOf(testOrdCrarge.Id),
			'newCard' => 'false',
			'chosenPaymentOptionId' => String.valueOf(pO1.Id)
		};

		resultChargeOrderNow = TouchCRAuraActionController.chargeOrderNow(JSON.serialize(chargeData));
		chargeOrderWrapper = (ResultWrapper)JSON.deserialize(resultChargeOrderNow, ResultWrapper.class);

		System.assertEquals('error', chargeOrderWrapper.status);
		System.assertEquals('Payment Option was not found', chargeOrderWrapper.error);
				
		chargeData = new Map<String, String>{
			'amount' => '2',
			'newCard' => 'false',
			'chosenPaymentOptionId' => String.valueOf(pO.Id)
		};

		resultChargeOrderNow = TouchCRAuraActionController.chargeOrderNow(JSON.serialize(chargeData));
		chargeOrderWrapper = (ResultWrapper)JSON.deserialize(resultChargeOrderNow, ResultWrapper.class);

		System.assertEquals('error', chargeOrderWrapper.status);    
		System.assertEquals('Order Id was not found', chargeOrderWrapper.error);    

		chargeData = new Map<String, String>{
			'amount' => '2',
			'orderId' => String.valueOf(testOrdCrarge.Id),
			'newCard' => 'true',
			'month' => '01',
			'year' => '20',
			'ccv' => '123',
			'cardNumber' => '4242424242424242'
		};

		resultChargeOrderNow = TouchCRAuraActionController.chargeOrderNow(JSON.serialize(chargeData));
		chargeOrderWrapper = (ResultWrapper)JSON.deserialize(resultChargeOrderNow, ResultWrapper.class);
		
		System.assertEquals('error', chargeOrderWrapper.status);
		//todo after add global setCustomSettings method on TouchCRHelper
		//System.assertEquals('success', chargeOrderWrapper.status);    
	}

	private class ResultWrapper {
		public String status { get; set; }
		public String error { get; set; }
		public Decimal amount { get; set; }
	}   


	//REFUND
	@isTest static void refundTestLight() {
		RecordType customerRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Customer_Account' AND IsPersonType = true];
		Account acc = new Account(
			RecordTypeId = customerRecordType.Id,
			LastName = 'Gerdegedi', FirstName = 'Itsig',
			PersonEmail = 'Gerdegedi.Itsig@gmail.com', Phone = '1234567890',
			BillingStreet = 'Vulture St, Woolloongabba', BillingCity = 'Brisbane',
			BillingState = 'Queensland', BillingPostalCode = '4102',
			BillingCountry = 'Australia', ShippingStreet = 'Vulture St, Woolloongabba',
			ShippingCity = 'Brisbane', ShippingState = 'Queensland',
			ShippingPostalCode = '4102', ShippingCountry = 'Australia'
		);
		insert acc;

		Order__c order = new Order__c(
			Charge_Amount__c = 1,
			Account__c = acc.Id
		);
		insert order;

		Order_Transaction__c testTrans = new Order_Transaction__c(
			Order__c = order.Id,
			Named_Agent__c = 'Test Agent Name',
			Type__c = 'Charge',
			Response_Status__c = 'Approved',
			Payment_Date__c = Datetime.now(),
			Amount__c = 1
		);
		insert testTrans;

		Decimal amount = TouchCRAuraActionController.getAmountRefund(testTrans.Id);
		System.assertEquals(1, amount);

		String resultRefund = TouchCRAuraActionController.refund(testTrans.Id, 1);
		System.assertEquals(true, resultRefund.containsIgnoreCase('Your transaction has been approved.'));
	}

	//AUTHORIZE
	@isTest static void authorizeTest() {
		Account acc = new Account(
			LastName = 'TestLastName', FirstName = 'TestFirstName',
			PersonEmail = '1290TestEmail0921@gmail.com', Phone = '1234567890',
			BillingStreet = 'TestBStreet', BillingCity = 'TestBCity',
			BillingState = 'Ontario', BillingPostalCode = '4102',
			BillingCountry = 'Canada',
			ShippingStreet = 'TestSStreet',
			ShippingCity = 'TestSCity', ShippingState = 'Ontario',
			ShippingPostalCode = '4102', ShippingCountry = 'Canada'
		);
		insert acc;

		Order__c order = new Order__c(
			Charge_Amount__c = 2,
			Account__c = acc.Id
		);
		insert order;

		Decimal amount = TouchCRAuraActionController.getAmountAuthorize(order.Id);
		System.assertEquals(2, amount);

		Map<String, String> authorizeData = new Map<String, String>{
			'cardExpirationMonth' => '01',
			'cardExpirationYear' => '2021',
			'ccv' => '123',
			'cardNumber' => '4242424242424242',
			'recordId' => String.valueOf(order.Id),
			'amount' => String.valueOf(amount)
		};

		String resultAuthorize = TouchCRAuraActionController.authorizeOrderNow(JSON.serialize(authorizeData));
		System.assertEquals(true, resultAuthorize.containsIgnoreCase('success'));
	}


}