mdapipkg/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{000000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/TouchCRConnection__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature__c</fullName>
        <label>Feature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>TouchCRConnection</label>
    <nameField>
        <label>TouchCRConnection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TouchCRConnections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/objects/TouchCRConnectionSetting__c.object
<CustomObject>
    <fields>
        <fullName>TouchCRConnection__c</fullName>
        <label>TouchCRConnection</label>
        <referenceTo>TouchCRConnection__c</referenceTo>
        <relationshipLabel>TouchCRConnectionSettings</relationshipLabel>
        <relationshipName>TouchCRConnectionSettings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>TouchCRConnectionSetting</label>
    <nameField>
        <label>TouchCRConnectionSetting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TouchCRConnectionSettings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/JetApiProcessingHelper.cls
public with sharing class JetApiProcessingHelper {

	public static final String FEATURENAME = 'Jet';

	public static final Set<String> BATCHES = new Set<String>{
		'JetApiConnectionManager', 'JetApiBatch'
	};

	public static final Set<String> REQUIRED_SETTINGS = new Set<String>{
		'Jet.salesfunnel',
		'Jet.' + JetApi.AUTH_USER,
		'Jet.' + JetApi.AUTH_PASS
	};

	public static Boolean isReadyToStart() {
		return (!JetApiProcessingHelper.isSyncInProgress() && JetApiProcessingHelper.hasActiveConnections());
	}

	public static Boolean hasActiveConnections() {
		return !getActiveConnectionsIds().isEmpty();
	}

	public static Boolean isSyncInProgress() {
		return ![
			SELECT Id, Status, ApexClass.Name
			FROM AsyncApexJob
			WHERE ApexClass.Name IN :BATCHES
			AND Status IN ('Holding', 'Queued', 'Preparing', 'Processing')
		].isEmpty();
	}


	//SAVE 'N LOAD
	public static Boolean loadSettingsForConnection(String connectionId) {
		// get persisted settings from connection
		TouchCRConnection__c persistedConnection = getConnectionById(connectionId);

		if (persistedConnection == null) {
			return false;
		}

		// collect persisted settings
		Map<String, String> connectionSettingsMap = new Map<String, String>();
		for (TouchCRConnectionSetting__c connSet : persistedConnection.TouchCRConnectionSettings__r) {
			connectionSettingsMap.put(connSet.Name, connSet.Value__c);
		}

		// prepare settings to load
		Map<String, String> setting = new Map<String, String>();
		// add settings from top level coonection
		setting.put('Jet.brand', persistedConnection.Brand__c);
		setting.put('Jet.connectionname', persistedConnection.Name);
		// add required settings from related connection settings
		for (String aSetting : REQUIRED_SETTINGS) {
			//check if all required settings are available
			if (connectionSettingsMap.containsKey(aSetting)) {
				setting.put(aSetting, connectionSettingsMap.get(aSetting));
			}
			else {
				return false;
			}
		}

		TouchCRHelper.setSettings(setting);

		return true;
	}

	public static Boolean saveSettingsForConnection(String connectionId) {
		// get persisted settings from connection
		TouchCRConnection__c persistedConnection = getConnectionById(connectionId);
		// get settings
		Map<String, String> currentSettings = TouchCRHelper.getSettings('Jet.');

		if (persistedConnection == null) {
			return false;
		}

		List<TouchCRConnectionSetting__c> settingsToUpdate = new List<TouchCRConnectionSetting__c>();

		// hold ids for connsettings for update
		Map<String, TouchCRConnectionSetting__c> connectionSettingsMap = new Map<String, TouchCRConnectionSetting__c>();
		for (TouchCRConnectionSetting__c connSet : persistedConnection.TouchCRConnectionSettings__r) {
			connectionSettingsMap.put(connSet.Name, connSet);
		}

		//check if all required settings are available
		for (String aSetting : REQUIRED_SETTINGS) {
			if (connectionSettingsMap.containsKey(aSetting)) {
				TouchCRConnectionSetting__c updatedSetting = connectionSettingsMap.get(aSetting);
				updatedSetting.Value__c = currentSettings.get(aSetting);
				settingsToUpdate.add(updatedSetting);
			}
			else {
				return false;
			}
		}
		Boolean isSettingsUpdateable = (
			TouchCRConnection__c.getSObjectType().getDescribe().isUpdateable() && // master object
				TouchCRConnectionSetting__c.getSObjectType().getDescribe().isUpdateable() && // detail object
				TouchCRConnectionSetting__c.Value__c.getDescribe().isUpdateable() && // detail object field
				TouchCRConnectionSetting__c.Name.getDescribe().isUpdateable() // detail object field
		);

		if (isSettingsUpdateable) {
			Database.update(settingsToUpdate, true);
			return true;
		}
		else {
			throw new PrivilegesException('Privileges Exception');
		}

		return false;
	}


	// GETTERS
	public static TouchCRConnection__c getConnectionById(String connectionId) {
		TouchCRConnection__c persistedConnection = [
			SELECT Name, Feature__c, Brand__c, (SELECT Id, Name, Value__c FROM TouchCRConnectionSettings__r)
			FROM TouchCRConnection__c
			WHERE Id = :connectionId
		];
		return (persistedConnection == null || persistedConnection.TouchCRConnectionSettings__r.isEmpty()) ? null : persistedConnection;
	}

	public static Set<String> getActiveConnectionsIds() {
		return new Map<String, TouchCRConnection__c>([
			SELECT Id
			FROM TouchCRConnection__c
			WHERE Feature__c = :FEATURENAME
			AND isActive__c = true
			ORDER BY Order__c ASC NULLS LAST, Brand__c ASC
		]).keySet();
	}

	public static String getPrevConnectionId() {
		return TouchCRHelper.getSettings('Jet.PrevConnectionId').get('Jet.PrevConnectionId');
	}

	public static Set<String> getProcessedConnectionsIds() {
		String result = TouchCRHelper.getSettings('Jet.ProcessedConnectionsIds').get('Jet.ProcessedConnectionsIds');
		return (result != null) ? new Set<String>(result.split(';')) : new Set<String>();
	}

	// SETTERS
	public static void cleanConnectionSettings() {
		TouchCRHelper.setSettings(
			new Map<String, String>{
				'Jet.PrevConnectionId' => null,
				'Jet.ProcessedConnectionsIds' => null
			}
		);
	}

	public static void setPrevConnectionId(String prevConnectionId) {
		TouchCRHelper.setSettings(
			new Map<String, String>{
				'Jet.PrevConnectionId' => prevConnectionId
			}
		);
	}

	public static void setPorcessedConnectionsIds(Set<String> processedConnections) {
		TouchCRHelper.setSettings(
			new Map<String, String>{
				'Jet.ProcessedConnectionsIds' => String.join(new List<String>(processedConnections), ';')
			}
		);
	}


	public with sharing class PrivilegesException extends Exception {
	}

}